#!/usr/bin/env node

var ARGS = process.argv.map(function (ARG) {
  return ARG.toLowerCase()
})

ARGS.shift()
ARGS.shift()
ARGS.unshift('npm')

try {
  require('child_process').execFileSync('/usr/bin/env', ARGS, {
    stdio: 'inherit'
  })
} catch (ERR) {
  process.exit(ERR.status)
}
